
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TkResLONGITUD = 19;
  public static final int TkResBINARIO = 5;
  public static final int TkSimMENORIGUAL = 37;
  public static final int TkSimPARENTESISCierra = 28;
  public static final int TkSimCorchetesArreglo = 33;
  public static final int TkResREDONDEO = 18;
  public static final int TkSimPARENTESISAbre = 27;
  public static final int TkResENTERO = 3;
  public static final int TkSimRESTA = 22;
  public static final int TkSimMAYORIGUAL = 39;
  public static final int TkResEJECUTAR = 14;
  public static final int TkSimCOMA = 46;
  public static final int TkResSI = 8;
  public static final int TkJDECIMAL = 49;
  public static final int TkSimCORCHETEAbre = 31;
  public static final int TkSimMODULO = 26;
  public static final int TkSimMULTIPLICACION = 23;
  public static final int TkJErChar = 51;
  public static final int TkSimIGUAL = 47;
  public static final int TkResSINO = 9;
  public static final int TkResIMPRIMIR = 10;
  public static final int TkSimLLAVECierra = 30;
  public static final int EOF = 0;
  public static final int TkJENTERO = 48;
  public static final int TkSimDOSPUNTOS = 44;
  public static final int TkSimIGUALIGUAL = 34;
  public static final int TkResRETORNO = 17;
  public static final int error = 1;
  public static final int TkSimLLAVEAbre = 29;
  public static final int TkSimOR = 40;
  public static final int TkResCADENA = 7;
  public static final int TkSimMENOR = 36;
  public static final int TkResCARACTER = 6;
  public static final int TkResVOID = 2;
  public static final int TkSimDIFERENTE = 35;
  public static final int TkResMIENTRAS = 11;
  public static final int TkSimMAS = 21;
  public static final int TkSimMAYOR = 38;
  public static final int TkResDOBLE = 4;
  public static final int TkSimPUNTO = 45;
  public static final int TkResACADENA = 20;
  public static final int TkResCONTINUAR = 16;
  public static final int TkResCORTAR = 15;
  public static final int TkSimPUNTOYCOMA = 43;
  public static final int TkResPARA = 12;
  public static final int TkResHACER = 13;
  public static final int TkJCADENA = 50;
  public static final int TkSimDIVISION = 24;
  public static final int TkJIdentificador = 52;
  public static final int TkSimMPOTENCIA = 25;
  public static final int TkSimINOT = 42;
  public static final int TkSimAND = 41;
  public static final int TkSimCORCHETECierra = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TkResVOID",
  "TkResENTERO",
  "TkResDOBLE",
  "TkResBINARIO",
  "TkResCARACTER",
  "TkResCADENA",
  "TkResSI",
  "TkResSINO",
  "TkResIMPRIMIR",
  "TkResMIENTRAS",
  "TkResPARA",
  "TkResHACER",
  "TkResEJECUTAR",
  "TkResCORTAR",
  "TkResCONTINUAR",
  "TkResRETORNO",
  "TkResREDONDEO",
  "TkResLONGITUD",
  "TkResACADENA",
  "TkSimMAS",
  "TkSimRESTA",
  "TkSimMULTIPLICACION",
  "TkSimDIVISION",
  "TkSimMPOTENCIA",
  "TkSimMODULO",
  "TkSimPARENTESISAbre",
  "TkSimPARENTESISCierra",
  "TkSimLLAVEAbre",
  "TkSimLLAVECierra",
  "TkSimCORCHETEAbre",
  "TkSimCORCHETECierra",
  "TkSimCorchetesArreglo",
  "TkSimIGUALIGUAL",
  "TkSimDIFERENTE",
  "TkSimMENOR",
  "TkSimMENORIGUAL",
  "TkSimMAYOR",
  "TkSimMAYORIGUAL",
  "TkSimOR",
  "TkSimAND",
  "TkSimINOT",
  "TkSimPUNTOYCOMA",
  "TkSimDOSPUNTOS",
  "TkSimPUNTO",
  "TkSimCOMA",
  "TkSimIGUAL",
  "TkJENTERO",
  "TkJDECIMAL",
  "TkJCADENA",
  "TkJErChar",
  "TkJIdentificador"
  };
}

